#document settings
<<<<<<< HEAD
title: Department of Labor Case Study
description: Lowering the Barrier to Entry to Government Data By Making It Accessible To Developers of all Skill Levels
url: http://project-open-data.github.com/Labor_OpenData_CaseStudy
repo_url: https://github.com/project-open-data/Labor_OpenData_CaseStudy
=======
title: Document Title Here
description: Document Description
url: http://project-open-data.github.com/jekyll-template
repo_url: https://github.com/project-open-data/jekyll-template
project_open_data_url: http://project-open-data.github.com
prose_url: http://project-open-data.github.com/prose/#
branch: gh-pages
>>>>>>> upstream/gh-pages

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true