#document settings
title: Document Title Here
description: Document Description
url: http://project-open-data.github.com/jekyll-template
repo_url: https://github.com/project-open-data/jekyll-template
project_open_data_url: http://project-open-data.github.com

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true